// Generated by scripts/sync-dsc-version.js from the repo-root DSC_VERSION
// file. Do not edit by hand — the CI drift check (scripts/check-dsc-version.sh)
// fails the build if this value stops matching the root file.
export const DSC_VERSION = '0.53.4';
